version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: build    # 只執行 build 階段
    container_name: frontend
    depends_on:
      - backend
    volumes:
      - frontend_dist:/app/dist    # 將 /app/dist 對應給 nginx 使用
    networks:
      - app-network

  simulator:
    build:
      context: ./simulator
    ports:
      - "8080:80"
    container_name: simulator
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html       # 掛載 frontend build 結果
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # 自定 nginx 設定
    depends_on:
      - frontend
      - simulator
    networks:
      - app-network

volumes:
  mongo_data:
  frontend_dist:

networks:
  app-network:
    driver: bridge
